
PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  job TEXT,
  role TEXT NOT NULL DEFAULT 'employee',
  department TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  last_login_at DATETIME,
  city TEXT,
  state TEXT,
  is_admin INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);

CREATE UNIQUE INDEX index_users_on_email ON users(email);
CREATE INDEX index_users_on_role ON users(role);
CREATE INDEX index_users_on_status ON users(status);

INSERT INTO users (first_name,last_name,email,phone,job,role,department,status,last_login_at,city,state,is_admin,created_at,updated_at) VALUES
('Alice','Ramirez','alice.ramirez@example.com','312-555-0101','Senior Rails Engineer','admin','Engineering','active',datetime('now','-2 days'),'Chicago','IL',1,datetime('now'),datetime('now')),
('Bob','Nguyen','bob.nguyen@example.com','312-555-0102','Team Lead','manager','Engineering','active',datetime('now','-1 days'),'Evanston','IL',0,datetime('now'),datetime('now')),
('Carol','Jenkins','carol.jenkins@example.com','312-555-0103','Frontend Engineer','engineer','Engineering','active',datetime('now','-3 days'),'Naperville','IL',0,datetime('now'),datetime('now')),
('David','Chen','david.chen@example.com','312-555-0104','Backend Engineer','engineer','Engineering','active',datetime('now','-5 days'),'Oak Park','IL',0,datetime('now'),datetime('now')),
('Evelyn','Carter','evelyn.carter@example.com','312-555-0105','QA Analyst','engineer','Engineering','inactive',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Frank','Olsen','frank.olsen@example.com','312-555-0106','Full Stack Dev','engineer','Engineering','active',datetime('now','-10 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Grace','Patel','grace.patel@example.com','312-555-0107','React Developer','engineer','Engineering','active',datetime('now','-12 hours'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Henry','Klein','henry.klein@example.com','312-555-0108','Junior Engineer','engineer','Engineering','pending',NULL,'Skokie','IL',0,datetime('now'),datetime('now')),
('Ivy','Santos','ivy.santos@example.com','312-555-0109','Product Engineer','engineer','Engineering','active',datetime('now','-7 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Jack','Ford','jack.ford@example.com','312-555-0110','Platform Engineer','engineer','Engineering','active',datetime('now','-4 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Karen','Diaz','karen.diaz@example.com','312-555-0111','Support Specialist','support','Support','active',datetime('now','-1 days'),'Aurora','IL',0,datetime('now'),datetime('now')),
('Leo','Hernandez','leo.hernandez@example.com','312-555-0112','Customer Support Rep','support','Support','active',datetime('now','-2 days'),'Joliet','IL',0,datetime('now'),datetime('now')),
('Mia','Park','mia.park@example.com','312-555-0113','Technical Support Rep','support','Support','inactive',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Noah','Foster','noah.foster@example.com','312-555-0114','Support Analyst','support','Support','active',datetime('now','-8 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Olivia','Gomez','olivia.gomez@example.com','312-555-0115','Support Engineer','support','Support','active',datetime('now','-6 days'),'Peoria','IL',0,datetime('now'),datetime('now')),
('Paul','Reed','paul.reed@example.com','312-555-0116','Sales Rep','sales','Sales','active',datetime('now','-3 days'),'Springfield','IL',0,datetime('now'),datetime('now')),
('Quinn','Morales','quinn.morales@example.com','312-555-0117','Account Executive','sales','Sales','active',datetime('now','-9 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Rita','Hughes','rita.hughes@example.com','312-555-0118','Sales Development Rep','sales','Sales','pending',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Sam','Barnes','sam.barnes@example.com','312-555-0119','Regional Sales','sales','Sales','active',datetime('now','-11 days'),'Peoria','IL',0,datetime('now'),datetime('now')),
('Tina','Vargas','tina.vargas@example.com','312-555-0120','Sales Ops','sales','Sales','active',datetime('now','-36 hours'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Uma','Hoffman','uma.hoffman@example.com','312-555-0121','HR Generalist','hr','HR','active',datetime('now','-2 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Victor','Baker','victor.baker@example.com','312-555-0122','People Ops','hr','HR','active',datetime('now','-14 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Wendy','Simmons','wendy.simmons@example.com','312-555-0123','HR Coordinator','hr','HR','inactive',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Xavier','Price','xavier.price@example.com','312-555-0124','Recruiter','hr','HR','active',datetime('now','-5 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Yara','Cooper','yara.cooper@example.com','312-555-0125','HR Business Partner','hr','HR','active',datetime('now','-1 days'),'Evanston','IL',0,datetime('now'),datetime('now')),
('Zane','Bell','zane.bell@example.com','312-555-0126','DevOps Engineer','engineer','Engineering','active',datetime('now','-2 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Adam','Sullivan','adam.sullivan@example.com','312-555-0127','SRE','engineer','Engineering','active',datetime('now','-4 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Bella','Ortiz','bella.ortiz@example.com','312-555-0128','Data Engineer','engineer','Engineering','pending',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Cody','Turner','cody.turner@example.com','312-555-0129','Support Engineer','support','Support','active',datetime('now','-3 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Dana','Riley','dana.riley@example.com','312-555-0130','Customer Care','support','Support','active',datetime('now','-6 days'),'Oak Park','IL',0,datetime('now'),datetime('now')),
('Eli','Griffin','eli.griffin@example.com','312-555-0131','Support Lead','support','Support','active',datetime('now','-9 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Faye','Mason','faye.mason@example.com','312-555-0132','Regional Manager','manager','Sales','active',datetime('now','-12 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Gavin','Pierce','gavin.pierce@example.com','312-555-0133','Eng Manager','manager','Engineering','active',datetime('now','-2 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Hazel','Watts','hazel.watts@example.com','312-555-0134','Support Manager','manager','Support','active',datetime('now','-8 hours'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Ian','Warren','ian.warren@example.com','312-555-0135','Contract Engineer','contractor','Engineering','active',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Jill','Boyd','jill.boyd@example.com','312-555-0136','Contract Designer','contractor','Engineering','active',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Kyle','Craig','kyle.craig@example.com','312-555-0137','Contract Sales','contractor','Sales','inactive',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Lena','Harper','lena.harper@example.com','312-555-0138','Contract Support','contractor','Support','active',datetime('now','-1 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Mark','Jordan','mark.jordan@example.com','312-555-0139','Director of Engineering','admin','Engineering','active',datetime('now','-4 hours'),'Chicago','IL',1,datetime('now'),datetime('now')),
('Nina','Dean','nina.dean@example.com','312-555-0140','Senior Engineer','engineer','Engineering','active',datetime('now','-3 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Omar','Perkins','omar.perkins@example.com','312-555-0141','Backend Engineer','engineer','Engineering','active',datetime('now','-7 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Piper','Hammond','piper.hammond@example.com','312-555-0142','Frontend Engineer','engineer','Engineering','active',datetime('now','-2 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Reid','Schmidt','reid.schmidt@example.com','312-555-0143','Integration Engineer','engineer','Engineering','inactive',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Sara','Lowe','sara.lowe@example.com','312-555-0144','Support Engineer','support','Support','active',datetime('now','-16 hours'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Tony','Briggs','tony.briggs@example.com','312-555-0145','Support Specialist','support','Support','active',datetime('now','-5 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Ursula','Douglas','ursula.douglas@example.com','312-555-0146','Account Exec','sales','Sales','active',datetime('now','-2 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Violet','Franklin','violet.franklin@example.com','312-555-0147','Sales Ops Analyst','sales','Sales','active',datetime('now','-10 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Wes','Gordon','wes.gordon@example.com','312-555-0148','HR Manager','hr','HR','active',datetime('now','-1 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
('Yvette','Harrington','yvette.harrington@example.com','312-555-0149','Recruiting Coordinator','hr','HR','pending',NULL,'Chicago','IL',0,datetime('now'),datetime('now')),
('Zelda','Ingram','zelda.ingram@example.com','312-555-0150','Mobile Engineer','engineer','Engineering','active',datetime('now','-6 days'),'Chicago','IL',0,datetime('now'),datetime('now')),
-- extra 50 with non-IL locations
('Alan','Morrison','alan.morrison@example.com','512-555-2001','Senior Backend Engineer','engineer','Engineering','active',datetime('now','-1 days'),'Austin','TX',0,datetime('now'),datetime('now')),
('Becca','Lyons','becca.lyons@example.com','512-555-2002','Frontend Engineer','engineer','Engineering','active',datetime('now','-3 days'),'Austin','TX',0,datetime('now'),datetime('now')),
('Chad','Fowler','chad.fowler@example.com','214-555-2003','Eng Manager','manager','Engineering','active',datetime('now','-5 days'),'Dallas','TX',0,datetime('now'),datetime('now')),
('Dia','Shah','dia.shah@example.com','713-555-2004','Support Engineer','support','Support','active',datetime('now','-2 days'),'Houston','TX',0,datetime('now'),datetime('now')),
('Ewan','Ross','ewan.ross@example.com','210-555-2005','Account Exec','sales','Sales','active',datetime('now','-7 days'),'San Antonio','TX',0,datetime('now'),datetime('now')),
('Farah','Iqbal','farah.iqbal@example.com','512-555-2006','HR Generalist','hr','HR','active',datetime('now','-4 days'),'Austin','TX',0,datetime('now'),datetime('now')),
('Gabe','Martin','gabe.martin@example.com','214-555-2007','Junior Engineer','engineer','Engineering','pending',NULL,'Dallas','TX',0,datetime('now'),datetime('now')),
('Holly','Daniels','holly.daniels@example.com','713-555-2008','Customer Support Rep','support','Support','active',datetime('now','-2 days'),'Houston','TX',0,datetime('now'),datetime('now')),
('Iris','Bates','iris.bates@example.com','210-555-2009','Platform Engineer','engineer','Engineering','active',datetime('now','-8 days'),'San Antonio','TX',0,datetime('now'),datetime('now')),
('Jon','Vega','jon.vega@example.com','469-555-2010','Director of Eng','admin','Engineering','active',datetime('now','-6 days'),'Plano','TX',1,datetime('now'),datetime('now')),
('Kara','Lopez','kara.lopez@example.com','415-555-3001','Senior React Dev','engineer','Engineering','active',datetime('now','-1 days'),'San Francisco','CA',0,datetime('now'),datetime('now')),
('Luca','Bianchi','luca.bianchi@example.com','510-555-3002','Support Specialist','support','Support','active',datetime('now','-4 days'),'Oakland','CA',0,datetime('now'),datetime('now')),
('Megan','Clarke','megan.clarke@example.com','323-555-3003','AE - West','sales','Sales','active',datetime('now','-5 days'),'Los Angeles','CA',0,datetime('now'),datetime('now')),
('Nolan','Price','nolan.price@example.com','619-555-3004','Full Stack Dev','engineer','Engineering','active',datetime('now','-2 days'),'San Diego','CA',0,datetime('now'),datetime('now')),
('Olive','Reese','olive.reese@example.com','916-555-3005','HR Partner','hr','HR','active',datetime('now','-9 days'),'Sacramento','CA',0,datetime('now'),datetime('now')),
('Pablo','Cruz','pablo.cruz@example.com','415-555-3006','Eng Manager','manager','Engineering','active',datetime('now','-3 days'),'San Francisco','CA',0,datetime('now'),datetime('now')),
('Queenie','Hsu','queenie.hsu@example.com','323-555-3007','Support Rep','support','Support','inactive',NULL,'Los Angeles','CA',0,datetime('now'),datetime('now')),
('Ronan','O''Brien','ronan.obrien@example.com','510-555-3008','Data Engineer','engineer','Engineering','active',datetime('now','-6 days'),'Oakland','CA',0,datetime('now'),datetime('now')),
('Sasha','Novak','sasha.novak@example.com','415-555-3009','Staff Engineer','engineer','Engineering','active',datetime('now','-12 hours'),'San Francisco','CA',0,datetime('now'),datetime('now')),
('Tarek','Mahmoud','tarek.mahmoud@example.com','310-555-3010','Sales Engineer','sales','Sales','active',datetime('now','-2 days'),'Los Angeles','CA',0,datetime('now'),datetime('now')),
('Una','Kelley','una.kelley@example.com','212-555-4001','Senior Engineer','engineer','Engineering','active',datetime('now','-1 days'),'New York','NY',0,datetime('now'),datetime('now')),
('Vik','Saxena','vik.saxena@example.com','718-555-4002','Support Lead','support','Support','active',datetime('now','-4 days'),'Brooklyn','NY',0,datetime('now'),datetime('now')),
('Willa','Hahn','willa.hahn@example.com','518-555-4003','AE - Northeast','sales','Sales','active',datetime('now','-5 days'),'Albany','NY',0,datetime('now'),datetime('now')),
('Ximena','Soto','ximena.soto@example.com','716-555-4004','Support Specialist','support','Support','active',datetime('now','-6 days'),'Buffalo','NY',0,datetime('now'),datetime('now')),
('Yusuf','Karim','yusuf.karim@example.com','212-555-4005','Eng Manager','manager','Engineering','active',datetime('now','-3 days'),'New York','NY',0,datetime('now'),datetime('now')),
('Zara','Mehta','zara.mehta@example.com','347-555-4006','Frontend Engineer','engineer','Engineering','pending',NULL,'Brooklyn','NY',0,datetime('now'),datetime('now')),
('Aiden','Cole','aiden.cole@example.com','305-555-5001','Support Rep','support','Support','active',datetime('now','-1 days'),'Miami','FL',0,datetime('now'),datetime('now')),
('Bella','Rossi','bella.rossi@example.com','407-555-5002','Support Engineer','support','Support','active',datetime('now','-4 days'),'Orlando','FL',0,datetime('now'),datetime('now')),
('Carlos','Mendez','carlos.mendez@example.com','813-555-5003','Account Exec','sales','Sales','active',datetime('now','-2 days'),'Tampa','FL',0,datetime('now'),datetime('now')),
('Daria','Stone','daria.stone@example.com','904-555-5004','Backend Engineer','engineer','Engineering','active',datetime('now','-7 days'),'Jacksonville','FL',0,datetime('now'),datetime('now')),
('Eliot','Grant','eliot.grant@example.com','305-555-5005','Sales Manager','manager','Sales','active',datetime('now','-5 days'),'Miami','FL',0,datetime('now'),datetime('now')),
('Fern','Owens','fern.owens@example.com','407-555-5006','HR Specialist','hr','HR','active',datetime('now','-3 days'),'Orlando','FL',0,datetime('now'),datetime('now')),
('Gina','Parker','gina.parker@example.com','813-555-5007','Support Rep','support','Support','inactive',NULL,'Tampa','FL',0,datetime('now'),datetime('now')),
('Hector','Vega','hector.vega@example.com','904-555-5008','DevOps Engineer','engineer','Engineering','active',datetime('now','-10 days'),'Jacksonville','FL',0,datetime('now'),datetime('now')),
('Isla','Murray','isla.murray@example.com','305-555-5009','Frontend Engineer','engineer','Engineering','active',datetime('now','-6 days'),'Miami','FL',0,datetime('now'),datetime('now')),
('Jace','Long','jace.long@example.com','813-555-5010','CTO','admin','Engineering','active',datetime('now','-2 days'),'Tampa','FL',1,datetime('now'),datetime('now')),
('Keira','Walsh','keira.walsh@example.com','206-555-6001','Senior Engineer','engineer','Engineering','active',datetime('now','-1 days'),'Seattle','WA',0,datetime('now'),datetime('now')),
('Liam','Douglas','liam.douglas@example.com','425-555-6002','Support Engineer','support','Support','active',datetime('now','-2 days'),'Bellevue','WA',0,datetime('now'),datetime('now')),
('Maddie','Young','maddie.young@example.com','206-555-6003','Account Exec','sales','Sales','active',datetime('now','-3 days'),'Seattle','WA',0,datetime('now'),datetime('now')),
('Noel','King','noel.king@example.com','425-555-6004','Platform Engineer','engineer','Engineering','active',datetime('now','-5 days'),'Redmond','WA',0,datetime('now'),datetime('now')),
('Owen','Sharp','owen.sharp@example.com','206-555-6005','HR Manager','hr','HR','active',datetime('now','-4 days'),'Seattle','WA',0,datetime('now'),datetime('now')),
('Priya','Raman','priya.raman@example.com','512-555-2011','Senior Engineer','engineer','Engineering','active',datetime('now','-2 days'),'Austin','TX',0,datetime('now'),datetime('now')),
('Quincy','Low','quincy.low@example.com','415-555-3011','Support Engineer','support','Support','active',datetime('now','-1 days'),'San Francisco','CA',0,datetime('now'),datetime('now')),
('Rae','Ng','rae.ng@example.com','212-555-4007','Data Engineer','engineer','Engineering','active',datetime('now','-2 days'),'New York','NY',0,datetime('now'),datetime('now')),
('Soren','White','soren.white@example.com','305-555-5011','Customer Support Rep','support','Support','active',datetime('now','-3 days'),'Miami','FL',0,datetime('now'),datetime('now')),
('Talia','Brandt','talia.brandt@example.com','713-555-2012','Director of Engineering','manager','Engineering','active',datetime('now','-7 days'),'Houston','TX',0,datetime('now'),datetime('now')),
('Uri','Levy','uri.levy@example.com','323-555-3012','Staff Engineer','engineer','Engineering','active',datetime('now','-6 days'),'Los Angeles','CA',0,datetime('now'),datetime('now')),
('Vera','Gold','vera.gold@example.com','718-555-4008','Sales Ops','sales','Sales','active',datetime('now','-5 days'),'Brooklyn','NY',0,datetime('now'),datetime('now')),
('Walt','Kramer','walt.kramer@example.com','904-555-5012','Support Specialist','support','Support','active',datetime('now','-4 days'),'Jacksonville','FL',0,datetime('now'),datetime('now')),
('Xander','Cho','xander.cho@example.com','210-555-2013','Junior Engineer','engineer','Engineering','pending',NULL,'San Antonio','TX',0,datetime('now'),datetime('now')),
('Yael','Fink','yael.fink@example.com','916-555-3013','HR Partner','hr','HR','active',datetime('now','-3 days'),'Sacramento','CA',0,datetime('now'),datetime('now')),
('Zeke','Armstrong','zeke.armstrong@example.com','206-555-6006','Senior DevOps Engineer','engineer','Engineering','active',datetime('now','-2 days'),'Seattle','WA',0,datetime('now'),datetime('now'));

PRAGMA foreign_keys = ON;

